sylius_grid:
    grids:
        setono_sylius_restock_notification_admin_notification:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_restock_notification.model.notification.class%"
            sorting:
                createdAt: desc
            fields:
                email:
                    type: string
                    label: setono_sylius_restock_notification.ui.email
                product_variant:
                    type: twig
                    label: sylius.ui.product
                    options:
                        template: "@SetonoSyliusRestockNotificationPlugin/admin/grid/field/product_variant.html.twig"
                state:
                    type: twig
                    label: setono_sylius_restock_notification.ui.state
                    options:
                        template: "@SetonoSyliusRestockNotificationPlugin/admin/grid/field/state.html.twig"
                createdAt:
                    type: datetime
                    label: setono_sylius_restock_notification.ui.created_at
                    sortable: ~
                sentAt:
                    type: datetime
                    label: setono_sylius_restock_notification.ui.sent_at
                    sortable: ~
                daysWaited:
                    type: twig
                    path: .
                    label: setono_sylius_restock_notification.ui.days_waited
                    options:
                        template: "@SetonoSyliusRestockNotificationPlugin/admin/grid/field/days_waited.html.twig"
            filters:
                email:
                    type: string
                    label: sylius.ui.email
                    options:
                        fields: [email]
                state:
                    type: select
                    label: sylius.ui.state
                    form_options:
                        choices:
                            setono_sylius_restock_notification.ui.states.error: !php/const Setono\SyliusRestockNotificationPlugin\Model\NotificationInterface::STATE_ERROR
                            setono_sylius_restock_notification.ui.states.pending: !php/const Setono\SyliusRestockNotificationPlugin\Model\NotificationInterface::STATE_PENDING
                            setono_sylius_restock_notification.ui.states.processing: !php/const Setono\SyliusRestockNotificationPlugin\Model\NotificationInterface::STATE_PROCESSING
                            setono_sylius_restock_notification.ui.states.sent: !php/const Setono\SyliusRestockNotificationPlugin\Model\NotificationInterface::STATE_SENT
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
