setono_sylius_restock_notification_admin_ajax_product_variant_by_phrase:
    path: /product-variants/search
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByPhraseWithoutLocale
                arguments:
                    phrase: $phrase
                    limit: 25

setono_sylius_restock_notification_admin_ajax_product_variant_by_code:
    path: /product-variants/code
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]
