setono_sylius_restock_notification_shop_restock_notification_request:
    path: /restock-notification-request
    methods: [POST]
    defaults:
        _controller: Setono\SyliusRestockNotificationPlugin\Controller\RestockNotificationRequestAction
